name: testing1
on:
  push:
    branches:
      - master
jobs:
  testingjob:
   runs-on: ubuntu-latest
   steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: hello world
      run: echo "Hello World"
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.access_key }}
        aws-secret-access-key: ${{ secrets.secret_access_key }}
        aws-region: us-east-1  # change as needed

    - name: Verify access
      run: aws sts get-caller-identity

    # Example: Upload to S3
    - name: Deploy to S3
      run: aws s3 cp ./index.html s3://testgitbuck/

    - name: Set S3 Bucket Policy
      run: |
       aws s3api put-bucket-policy \
         --bucket testgitbuck \
         --policy file://.github/policies/public-policy.json

